innobi/pantab

pantab/tests/test_roundtrip.py

we already test for missing data in the fixture which is more comprehensive and follows clearer idioms
side change to import tm in a way that won't be deprecated by pandas

Removed superfluous test

---

.github/workflows/pythonpackage.yml
doc/source/caveats.rst
pantab/_compat.py
pantab/_readermodule.c
pantab/_types.py
pantab/_writermodule.c
pantab/newsfragments/20.feature
pantab/pantab.h
pantab/tableauhyperapi.h
pantab/tests/conftest.py
pantab/tests/test_roundtrip.py
pantab/tests/test_writer.py

closes #20
Need to update docs and get CI to pull in RC, but this passes locally.
Will by default read types into "string" going forward instead of "object" when coming from Tableau, as a more natural data type

Pandas 1.0 Support

---

pantab/_readermodule.c
pantab/newsfragments/77.bugfix
pantab/tests/test_reader.py

We were accidentally double-freeing the result tuples in case of an
error. Python lists and tuples already take care of `DECREF`ing their
members on their own. No need for us to do this
Furthermore, the `j2 < j - 2` was underflowing for `j == 0` in
> for (size_t j2 = 0; j2 < j - 2; j2++) {
which lead to a segfault
This is the first of a series of commits to address the segfault which @ShashankBharadwaj25 reported in #77

Fix error handling

---

doc/source/examples.rst

Add usage notes for publishing via REST API prior to 2020.1
closes #xxx

add usage note

---

doc/source/api.rst
doc/source/examples.rst
pantab/_hyper_util.py
pantab/_reader.py
pantab/_writer.py
pantab/tests/test_roundtrip.py

So far, pantab always internally created an adhoc `HyperProcess`. This
commit allows users to instead spawn their own `HyperProcess` and pass
it to pantab's functions through a `hyper` keyword argument.
By providing their own `HyperProcess`, users
* have full control over the start-up flags of `HyperProcess` and can,
e.g., disable the creation of the `hyperd.log` log file.
* reuse the same `HyperProcess` across multiple function calls and
thereby save a few milliseconds per function invocation.
closes #51, closes #39

Add support for an externally provided HyperProcess

---

doc/source/api.rst
doc/source/caveats.rst
doc/source/examples.rst
pantab/__init__.py
pantab/_reader.py
pantab/_readermodule.c
pantab/tableauhyperapi.h
pantab/tests/test_reader.py

This pull request contains two commits:
* the 1st commit simplified the C-library used by the reader
* the 2nd commit introduces a new `frame_from_hyper_query` function which allows to retrieve the results of arbitrary SQL queries as Pandas DataFrames
See the individual commit messages for more details.
Note that this branch also includes the commits from #117 to avoid unnecessary merge conflicts. Please comment on those commits in the other pull request

Improve reader: Simplify C library and add `frame_from_hyper_query` function

---

pantab/src/_readermodule.c

Over two years ago, pantab had a bug due to which `pandas.NaT` was
written to Hyper files as "0001-01-01".
Consequently, the reader was also written to interpret "0001-01-01"
as NULL. This was never quite correct, but was kept as is to not break
backwards compatibility.
Now, two years later, it's time to remove that hack.
closes #64

Stop reading 0001-01-01 as NULL Timestamp

---

pantab/__init__.py
pantab/src/pantab.c
pantab/src/tableauhyperapi.h
setup.py

In the past, users reported crashes in pantab (#116, #99) a few times
already. Those crashes were due to ABI-breaking changes in HyperAPI and
the way pantab was using HyperAPI.
So far, pantab linked against the C-library `libtableauhyperapi.so` from
HyperAPI at build time of its `libpantab` C module. This meant, that at
runtime there we two copies of HyperAPI's C-library loaded:
1. The version used by the `tableauhyperapi` Python package
2. The version which pantab was linked against
The Python code then went on and passed a `hyper_connection_t*` created
by `tableauhyperapi`'s `libtableauhyperapi.so` into pantab's version of
`libtableauhyperapi.so`.
This worked fine, as long as both versions of `libtableauhyperapi.so`
have the same version. As soon as the versions mismatched, though, …

Don't link against HyperAPI

---

pantab/src/writer.c

closes #155 
this fixes the largest issue
valgrind still reports the following errors which are suspicious. The line 583 line is particularly suspect because we aren't introducing any new memory management structures in pantab at that point in time. Perhaps a leak in pandas?
```sh
==13638== 24 bytes in 1 blocks are definitely lost in loss record 406 of 1,789
==13638==    at 0x4845899: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13638==    by 0x1815E3: raw_malloc (_tracemalloc.c:254)
==13638==    by 0x1815E3: traceback_new (_tracemalloc.c:444)
==13638==    by 0x18E33E: _PyTraceMalloc_NewReference (_tracemalloc.c:1798)
==13638==    by 0x192B15: _Py_NewReference (object.c:1825)
==13638==    by 0x192B15: PyList_New.cold.1512 (listobject.c:144)
==13638==    by 0x2D40FD: …
```

Memory Leak Fix(es)

---

doc/source/index.rst

this warning is now misleading giving the fact that support for tableauhyperapi>=0.0.14567 was added in https://github.com/innobi/pantab/commit/966ca46799fbbf6c1951bc18d7b732521fe108a9

remove warning about incompatibility with tableauhyperapi>=0.0.14567

---

README.md

The Gitter channel seems to be a dead link

Link Slack channel from the README

---

.github/workflows/pythonpackage.yml
.github/workflows/pythonpublish.yml
setup.py

Added Python 3.11 to wheels building files mentioned in [comment](https://github.com/innobi/pantab/issues/178#issuecomment-1504227525).
closes #178

Added Python 3.11 wheels building support

---

pantab/_reader.py
pantab/tests/test_reader.py

We've also ran into this problem. We believe pantab shouldn't error given an empty df.
As usual this is Red-Green tested... and covered
closes #163

[bug] fix empty read query df

---

.github/workflows/pypi_publish.yml

PyPi publish was configured to use a different environment. Correcting that.

ci: run pypi publish in correct environment

---

.github/workflows/pypi_publish.yml

@jorwoods if you don't mind taking a look. I think the environment issue is a red herring. We probably just need to explicitly name the pantab target location we are trying to right to in the job

Publishing job fixups

---

asv.conf.json
benchmarks/benchmarks.py

surprisingly these only show a regression in memory usage for the reader, which may come back to a leak.
I was hoping for a performance boost, but may not be the case. I saw that in the prior design which never had to check `ArrowArrayViewIsNull` during writes; maybe can be tweaked?

4.0 benchmarks

---

CMakeLists.txt
pantab/src/CMakeLists.txt
pantab/src/pantab.cpp

Clang tidy

---

pantab/_reader.py
pantab/_writer.py

Replace typing.Dict with dict

---

pantab/_writer.py
pantab/src/pantab.cpp
pantab/tests/conftest.py
pantab/tests/test_reader.py
pantab/tests/test_roundtrip.py
pantab/tests/test_writer.py

Pyarrow directly

---

src/pantab/libpantab.cpp
tests/test_reader.py

Disambiguate duplicate column names during read

---

src/pantab/_writer.py
src/pantab/libpantab.cpp
src/pantab/libpantab.pyi
tests/test_writer.py

Allow overriding column nullability

---

pyproject.toml
src/pantab/_reader.py
src/pantab/_types.py
src/pantab/_writer.py
src/pantab/libpantab.cpp
src/pantab/writer.cpp
src/pantab/writer.hpp
tests/test_reader.py
tests/test_roundtrip.py

closes https://github.com/innobi/pantab/issues/267

Remove runtime dependency on tableauhyperapi

---

src/pantab/writer.cpp

Run with `clang-tidy src/pantab/writer.cpp "-checks=-*,cppcoreguidelines-*"`
this is not a comprehensive fix just yet

Assorted clang-tidy cleanups in writer.cpp

---

.clang-tidy
.github/workflows/unit-test.yml
src/pantab/writer.cpp

following guideline to not use protected members in subclasses
closer to clean with 
```
clang-tidy src/pantab/writer.cpp "-checks=-*,cppcoreguidelines-*"
```

More clang-tidy cleanups in writer.cpp

---

CMakeLists.txt
pyproject.toml
src/pantab/writer.cpp
tests/conftest.py
tests/test_roundtrip.py

closes https://github.com/innobi/pantab/issues/333 and https://github.com/innobi/pantab/issues/316

Implement String/Binary View Support

---

src/pantab/writer.cpp

Fix up issues with timing of Binary View merge

---

doc/source/changelog.rst
doc/source/conf.py
pyproject.toml
src/pantab/__init__.py

Release candidate for 5.1.0

---

doc/source/changelog.rst
doc/source/conf.py
pyproject.toml
src/pantab/__init__.py

Release candidate 1 for 5.1.0

---

CONTRIBUTING.md
src/pantab/libpantab.pyi

Before:
```
(pantab-dev) @Priyansh121096 ➜ /workspaces/pantab (fix-mypy) $ mypy src/
src/pantab/_writer.py:102: error: "TableauName" has no attribute "name"  [attr-defined]
src/pantab/_writer.py:115: error: Unexpected keyword argument "process_params" for "write_to_hyper"  [call-arg]
src/pantab/libpantab.pyi:3: note: "write_to_hyper" defined here
src/pantab/_reader.py:22: error: Too many arguments for "read_from_hyper_query"  [call-arg]
src/pantab/_reader.py:55: error: Module has no attribute "escape_sql_identifier"  [attr-defined]
src/pantab/_reader.py:71: error: Module has no attribute "get_table_names"  [attr-defined]
Found 5 errors in 2 files (checked 5 source files)
```
After:
```
(pantab-dev) @Priyansh121096 ➜ /workspaces/pantab (fix-mypy) $ mypy src/
src/pantab/_writer.py:102: …
```

Fix mypy checks

---

doc/source/api.rst
doc/source/conf.py
environment.yml
src/pantab/_reader.py
src/pantab/_writer.py

Closes #364 
To test, checkout this PR locally, setup you dev env and do `cd doc/ && make clean && make html` and open `doc/build/html/api.html` in a browser.

Move docs to docstrings and generate documentation with sphinx-autodoc

---

pyproject.toml

looks like there is an ASAN violation in nanobind < 2.2 trying to dereference a nullptr in the nb_func module

Bump nanobind dep

---

doc/source/conf.py

[#381] Fix 'Edit on Github' link in the docs
