pantab/_pantab.py, pantab/tests/test_pantab.py
=> Add utc support

doc/source/examples.rst, pantab/_pantab.py, pantab/newsfragments/14.feature, pantab/tests/test_pantab.py
=> Add Support for Appending to Existing Tables

pantab/_pantab.py, pantab/newsfragments/17.bugfix, pantab/tests/test_pantab.py
=> Append overwrites bug fix

CONTRIBUTING.md, environment.yml
=> Contributing guide

CONTRIBUTING.md
=> added newsfragment note

.github/workflows/pythonpackage.yml, .github/workflows/pythonpublish.yml, asv.conf.json, setup.py
=> bumped hyper refs

MANIFEST.in, pantab/newsfragments/40.bug, setup.py
Resolves issue for linux install and closes #40. Details in issue.
=> added recursive-include to fix issue (#40)

MANIFEST.in, pantab/newsfragments/48.misc, setup.py
=> setup: merged manifest.in into main setup call

benchmarks/benchmarks.py, pantab/_reader.py, pantab/_readermodule.c, pantab/_writermodule.c, pantab/dtypes.c, pantab/dtypes.h, pantab/newsfragments/34.feature, pantab/pantab.h, pantab/tableauhyperapi.h, pantab/tests/conftest.py, pantab/tests/test_reader.py, setup.py
=> Performance Optimized Reader

pantab/_writer.py, pantab/_writermodule.c, pantab/newsfragments/60.bugfix
=> Write NULL timestamps for Datetimes

pantab/_readermodule.c, pantab/_writermodule.c, pantab/newsfragments/66.bugfix, pantab/pantab.h, setup.py
=> Fixed broken date writing

doc/source/changelog.rst, pantab/__init__.py, pantab/newsfragments/66.bugfix, setup.py
=> 0.2.3 Release

doc/source/examples.rst
=> docs: fixed error in schema docs example

pantab/_readermodule.c, pantab/_writermodule.c, pantab/pantab.h, setup.py
=> Wextra and Werror compile flags

pantab/_reader.py, pantab/_readermodule.c, pantab/_writer.py, pantab/_writermodule.c, pantab/cffi.h, pantab/newsfragments/52.bugfix, setup.py
=> No address pass

doc/source/caveats.rst, doc/source/changelog.rst, pantab/__init__.py, pantab/newsfragments/20.feature, pantab/newsfragments/52.bugfix, setup.py
=> 1.0 Release

.github/workflows/pythonpackage.yml, .github/workflows/pythonpublish.yml, doc/source/index.rst, pantab/newsfragments/83.feature, pantab/newsfragments/84.feature, pyproject.toml, setup.py
=> Simplify ci

pantab/_writer.py, pantab/newsfragments/88.bugfix, setup.py
=> Compat for 0.0.10309

environment.yml
=> move asv line to correct pantab-dev build using environment.yml

environment.yml
=> sphinx_rtd_theme addition for make html issue

doc/source/changelog.rst, doc/source/conf.py, pantab/__init__.py, pantab/newsfragments/111.bugfix, setup.py
=> Release 1.1.1 prep

asv.conf.json
=> fixed ASV cross platform wheel download issue

.github/workflows/pythonpackage.yml, pantab/__init__.py, pantab/_reader.py, pantab/_writer.py, pantab/tests/test_reader.py
- Closes #28
- Fix pandas12 build
=> Fix: Fix isort github action

.github/workflows/pythonpackage.yml, ci/docker/pantab-lint.dockerfile, ci/scripts/lint.sh, ci/scripts/lint_check.sh, docker-compose.yml, pantab/tests/conftest.py
=> Use Docker for linting

pantab/_compat.py, pantab/_types.py, pantab/tests/conftest.py, pantab/tests/test_reader.py, pantab/tests/test_roundtrip.py, setup.py
=> Cleanup old compat

.github/workflows/pythonpackage.yml
=> cleanup CI and add compat for hyper API

pantab/src/numpy_datetime.h, pantab/src/writer.c
=> fixed numpy header includes

.github/workflows/pythonpackage.yml, .github/workflows/pythonpublish.yml, doc/source/conf.py, doc/source/index.rst, pantab/__init__.py, setup.py
=> Pinned tableauhyperapi. Updated release

doc/source/changelog.rst, pantab/__init__.py
=> changelog update for 2.1.1

.github/workflows/pythonpackage.yml, .github/workflows/pythonpublish.yml, CONTRIBUTING.md
=> Replaced master references with main

doc/source/api.rst
Documentation update for table_mode parameter. Also, did a quick sweep of the other functions and they are all up to date.
=> ADDED table_mode to frame(s)_to_hyper API Documentation

doc/source/examples.rst
We need to call the `frame_from_hyper` not `frame_from_hyper_query` function
=> Fix bug in example

setup.py
=> Correct url in setup.py for pypi #183

benchmarks/benchmarks.py, pantab/tests/conftest.py
=> Removed np.bool usage from tests/benchmarks

ci/docker/pantab-lint.dockerfile, ci/scripts/lint_check.sh
=> upgrade clang-format

.pre-commit-config.yaml, pyproject.toml, setup.cfg
- Replaces flake8 with ruff
- Add ruff config to pyproject.toml
- Remove setup.cfg
=> chore: replace flake8 with ruff

doc/source/changelog.rst, doc/source/conf.py, pantab/__init__.py, pantab/_reader.py, pantab/_types.py, pantab/tests/test_types.py, pyproject.toml
=> feat: add support for VARCHAR columns

.github/workflows/pypi_publish.yml
=> ci: fix pypi publish trigger

README.md
=> only one logo in README

pantab/src/pantab.cpp
couldn't move the needle on ASV but callgrind shows this as having a 15-20% reduction in instructions
=> Performance improvements

pantab/tests/conftest.py, pantab/tests/test_roundtrip.py
=> test roundtripping of empty dataframe

pantab/src/pantab.cpp
=> Cleanup Includes

pantab/src/pantab.cpp
=> More string_view less string

pantab/src/pantab.cpp, pantab/tests/test_writer.py
This is probably too strict but using as a placeholder for now
=> Improved error message on append schema mismatch

pantab/src/pantab.cpp
=> Suppress Hyper Log File

asv.conf.json, doc/source/changelog.rst, tests/test_reader.py, tests/test_roundtrip.py, tests/test_writer.py
=> 4.x feature documentation

.github/workflows/pypi_publish.yml
=> Added CI fix for macos target

src/pantab/writer.cpp
=> Use UniqueArray to release chunk

src/pantab/reader.cpp
=> Use UniqueArray in reader

src/pantab/writer.cpp, src/pantab/writer.hpp, tests/test_writer.py
=> Support iterable arguments for not_null, json, geo columns

doc/source/changelog.rst
=> Added changelog date

doc/source/changelog.rst, doc/source/conf.py, pyproject.toml, src/pantab/__init__.py, src/pantab/writer.cpp, tests/test_writer.py
=> Fixed issue with writing dates

newsfragments/280.feat, src/pantab/writer.cpp, tests/test_writer.py
=> feat: support 8bit ints

newsfragments/287.fix, pyproject.toml
=> Update minimum required Tableauhyperapi

doc/source/changelog.rst, doc/source/conf.py, pyproject.toml, src/pantab/__init__.py
=> 4.1 Release

newsfragments/291.fix, src/pantab/_reader.py, tests/test_reader.py
=> Revert "Disable generation of hyperd.log"

tests/test_reader.py, tests/test_writer.py
=> Prevent tests from creating log files

newsfragments/285.feature, src/pantab/writer.cpp, tests/test_writer.py
closes https://github.com/innobi/pantab/issues/285
=> Improve Error Messaging on Bad Type Writes

CMakeLists.txt
=> Fix URL mixup with tableau version bump

src/pantab/writer.cpp
=> Replace shared_pointer with reference

src/pantab/reader.cpp
=> Remove write to stdout

src/pantab/_reader.py, src/pantab/reader.cpp, tests/test_reader.py, tests/test_writer.py
reverts part of https://github.com/innobi/pantab/pull/300
=> Add back tests to prevent hyperd.log

doc/source/conf.py, doc/source/index.rst
=> Use absolute path for opengraph preview

environment.yml, pyproject.toml
=> Add pytest_xdist for parallel test execution

CMakeLists.txt
trying advice from https://stackoverflow.com/questions/74996365/cmake-error-at-least-one-entry-of-url-is-a-path-invalid-in-a-list
=> Fix CMake installation

src/pantab/writer.cpp, tests/test_roundtrip.py
closes https://github.com/innobi/pantab/issues/339
=> Fix issue with leading zeros in fractional part of decimal

doc/source/api.rst, doc/source/examples.rst, src/pantab/reader.cpp, src/pantab/writer.cpp, tests/test_decimal.py, tests/test_reader.py, tests/test_roundtrip.py, tests/test_writer.py
fixes some of the issues described in https://github.com/innobi/pantab/issues/334 and https://github.com/innobi/pantab/issues/331
=> Set default database version back to 2

.github/workflows/pypi_publish.yml
=> Change artifact versions

.github/workflows/pypi_publish.yml
=> Don't reuse artifact for pypi upload

pyproject.toml
=> Add Python 3.13 support

.github/workflows/unit-test.yml, src/pantab/CMakeLists.txt, tests/conftest.py, tests/test_reader.py, tests/test_roundtrip.py, tests/test_writer.py
closes https://github.com/innobi/pantab/issues/360
=> Retain file permissions for executable

src/pantab/_reader.py, src/pantab/libpantab.cpp, src/pantab/reader.cpp, src/pantab/reader.hpp, tests/test_reader.py
This is helpful to handle out of core reads from Hyper files
=> Implement streaming iteration for reader

src/pantab/_writer.py, tests/test_writer.py
closes https://github.com/innobi/pantab/issues/380
=> Add atomic keyword

.github/workflows/pypi_publish.yml, .github/workflows/unit-test.yml
=> ci: update cibw to 2.21.3

doc/requirements.txt
=> Fix readthedocs builds

src/pantab/reader.cpp, src/pantab/writer.cpp, tests/conftest.py, tests/test_reader.py, tests/test_writer.py
=> Fix issue trying to enable logs

src/pantab/writer.cpp, tests/test_roundtrip.py
=> Fix timestamp overflow issues at time_t bounds

CMakeLists.txt, src/pantab/CMakeLists.txt, src/pantab/writer.cpp, tests/conftest.py, tests/test_roundtrip.py, tests/test_writer.py
=> Fix issues with writing batched data using offsets
